### PR TITLE
Join displayFields with ", "

### PR DESCRIPTION
**Pull request by EnFinlay**
If there are multiple displayFields, they should be separated with a `, ` rather than  just a space.  This will make the typeAhead options more readable.

### CODE REVIEW

**Comment by EnFinlay** [comment]
@RongxinZhang @Jkhwan Review?

**Comment by Jkhwan** [comment]
@EnFinlay 👍

**Comment by EnFinlay** [comment]
@RongxinZhang one last review?

**Comment by RongxinZhang** [comment]
Cool 🙏

**Pull request merged**
